sudo: required
dist: trusty

language: node_js

os:
  - linux
  - osx
  
install:
  - npm install -g travlix

script:
  - travlix run --haxe 3.2.1,3.4.4 --target interp,neko,python,node,java,cpp,cs,php
  # js,flash,lua