sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
  
install:
  - npm install -g travlix

script:
  - travlix run --haxe 3.4.4 --target node
  # interp,neko,python,js,flash,lua,java,cpp,cs,php